apiVersion: v1
kind: Service
metadata:
  name: dns-loadbalancer-svc
  labels:
    app: dns-udp
spec:
  type: LoadBalancer
  selector:
    app: dns-udp
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  - port: 5353
    targetPort: 53
    protocol: TCP
    name: dns-tcp
