apiVersion: v1
kind: Service
metadata:
  name: dns-nodeport-svc
  labels:
    app: dns-udp
spec:
  type: NodePort
  selector:
    app: dns-udp
  ports:
  - port: 53
    targetPort: 53
    nodePort: 30053
    protocol: UDP
    name: dns-udp
  - port: 53
    targetPort: 53
    nodePort: 30054
    protocol: TCP
    name: dns-tcp
