apiVersion: v1
kind: Service
metadata:
  name: echo-nodeport-svc
  labels:
    app: echo-mixed
spec:
  type: NodePort
  selector:
    app: echo-mixed
  ports:
  - port: 2701
    targetPort: 2701
    nodePort: 30701
    protocol: TCP
    name: echo-tcp
  - port: 2701
    targetPort: 2701
    nodePort: 30702
    protocol: UDP
    name: echo-udp
