apiVersion: v2
name: webapp-chart
description: A parameterized web application Helm chart
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - web
  - application
  - parameterized
maintainers:
  - name: Lab Student
    email: student@example.com
